import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import test from "node:test";

test("comparison builds anonymous audit bundles and honest resource-only verdicts", async (t) => {
  const out=await mkdtemp(path.join(os.tmpdir(),"pilot-comparison-")); t.after(()=>rm(out,{recursive:true,force:true}));
  const privateDir=path.join(out,"private"), run=spawnSync(process.execPath,["scripts/compare-routing-pilot.mjs","--report-root","/private/tmp/routing-pilot-live","--output",path.join(out,"report.json"),"--audit-dir",path.join(out,"audit"),"--private-dir",privateDir],{encoding:"utf8"}); assert.equal(run.status,0,run.stderr);
  const report=JSON.parse(await readFile(path.join(out,"report.json"))), bundles=JSON.parse(await readFile(path.join(out,"audit","bundles.json"),"utf8"));
  assert.equal(report.rows.length,9); assert.equal(report.currency.availability,"unavailable"); assert.equal(report.verdicts.deterministic_oracle_parity,"proven"); assert.equal(report.verdicts.general_quality,"not-proven"); assert.equal(report.verdicts.broad_efficiency_savings,"not-proven"); assert.equal(report.comparisons.delegation_overhead.length,3); assert.equal(report.comparisons.cheaper_model_routing_effect.length,3); assert.equal(bundles.candidates.length,9);
  const doctor=report.comparisons.delegation_overhead.find((row)=>row.task==="doctor-semantic-role"), single=report.rows.find((row)=>row.task==="doctor-semantic-role"&&row.arm==="single-sol-medium"), multi=report.rows.find((row)=>row.task==="doctor-semantic-role"&&row.arm==="all-sol-multi-agent"); assert.equal(doctor.delta.output_tokens,multi.metrics.output_tokens-single.metrics.output_tokens);
  assert.match(JSON.stringify(bundles),/candidate-/); assert.doesNotMatch(JSON.stringify(bundles),/gpt-5\.6|routed-sol|all-sol|single-sol|session_id|input_tokens/);
  assert.deepEqual((await readdir(path.join(out,"audit"))).sort(),[".git","audit-prompt.txt","audit-schema.json","bundles.json"]); assert.doesNotMatch(JSON.stringify(await readdir(path.join(out,"audit"))),/private|mapping|model|session|usage/); assert.equal(spawnSync("git",["-C",path.join(out,"audit"),"rev-parse","--is-inside-work-tree"],{encoding:"utf8"}).stdout.trim(),"true");
  const missingRaw=spawnSync(process.execPath,["scripts/compare-routing-pilot.mjs","--report-root","/private/tmp/routing-pilot-live","--output",path.join(out,"missing.json"),"--audit-dir",path.join(out,"audit"),"--private-dir",privateDir,"--import-result",path.join(out,"none.json")],{encoding:"utf8"}); assert.notEqual(missingRaw.status,0);
  const sessions=path.join(out,"sessions","2026","07","24"), resultPath=path.join(out,"audit","audit-result.json"), rawPath=path.join(out,"audit","audit-raw.jsonl"), thread="audit-thread", usage={input_tokens:1,cached_input_tokens:0,output_tokens:1,reasoning_output_tokens:0}; await mkdir(sessions,{recursive:true}); await writeFile(resultPath,JSON.stringify({schema_version:1,candidates:bundles.candidates.map((candidate)=>({label:candidate.label,acceptance:true,critical_findings:[],major_findings:[],rationale:"ok"}))})); await writeFile(rawPath,`${JSON.stringify({timestamp:"2026-07-24T00:00:00.000Z",type:"thread.started",thread_id:thread})}\n${JSON.stringify({type:"turn.completed",usage})}\n`);
  const session=(model,effort,total=usage)=>[{type:"session_meta",payload:{id:thread}},{type:"turn_context",payload:{model,effort}},{type:"event_msg",payload:{type:"token_count",info:{total_token_usage:total}}},{type:"event_msg",payload:{type:"task_complete"}}].map(JSON.stringify).join("\n")+"\n"; const sessionPath=path.join(sessions,"audit.jsonl");
  await writeFile(sessionPath,session("gpt-5.6-terra","medium")); const common=["scripts/compare-routing-pilot.mjs","--report-root","/private/tmp/routing-pilot-live","--output",path.join(out,"imported.json"),"--audit-dir",path.join(out,"audit"),"--private-dir",privateDir,"--import-result",resultPath,"--import-raw",rawPath,"--sessions-root",path.join(out,"sessions")]; assert.notEqual(spawnSync(process.execPath,common,{encoding:"utf8"}).status,0);
  await writeFile(sessionPath,session("gpt-5.6-sol","low")); assert.notEqual(spawnSync(process.execPath,common,{encoding:"utf8"}).status,0); await writeFile(sessionPath,session("gpt-5.6-sol","medium",{...usage,input_tokens:2})); assert.notEqual(spawnSync(process.execPath,common,{encoding:"utf8"}).status,0); await writeFile(sessionPath,session("gpt-5.6-sol","medium"));
  const validAudit=JSON.parse(await readFile(resultPath)); const reject=(name,audit,extra=[])=>{const file=path.join(out,`${name}.json`); return writeFile(file,JSON.stringify(audit)).then(()=>assert.notEqual(spawnSync(process.execPath,[...common.slice(0,common.indexOf("--import-result")+1),file,...common.slice(common.indexOf("--import-raw")),...extra],{encoding:"utf8"}).status,0));}; const duplicate={...validAudit,candidates:[...validAudit.candidates.slice(0,-1),validAudit.candidates[0]]}; await reject("duplicate",duplicate); await reject("extra",{...validAudit,candidates:[...validAudit.candidates.slice(0,-1),{...validAudit.candidates.at(-1),label:"candidate-extra"}]}); await reject("missing",{...validAudit,candidates:validAudit.candidates.slice(0,-1)});
  const duplicateMapping=JSON.parse(await readFile(path.join(privateDir,"private-mapping.json"))); const mapLabels=Object.keys(duplicateMapping.labels); duplicateMapping.labels[mapLabels[1]]=duplicateMapping.labels[mapLabels[0]]; const duplicateMappingPath=path.join(out,"duplicate-mapping.json"); await writeFile(duplicateMappingPath,JSON.stringify(duplicateMapping)); await reject("valid-with-duplicate-mapping",validAudit,["--private-mapping",duplicateMappingPath]);
  const imported=spawnSync(process.execPath,common,{encoding:"utf8"}); assert.equal(imported.status,0,imported.stderr); const importedReport=JSON.parse(await readFile(path.join(out,"imported.json"))); assert.equal(importedReport.blind_audit.session_receipt.model,"gpt-5.6-sol"); assert.equal(importedReport.blind_audit.session_receipt.effort,"medium"); assert.deepEqual(importedReport.blind_audit.session_receipt.usage,usage); assert.equal(importedReport.verdicts.benchmark_quality_parity,"proven"); assert.equal(importedReport.verdicts.general_quality,"not-proven");
});
